-- MySQL Script generated by MySQL Workbench
-- mer. 09 juin 2021 13:10:54 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema survey
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema survey
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `survey` DEFAULT CHARACTER SET latin1 ;
USE `survey` ;

-- -----------------------------------------------------
-- Table `survey`.`carreer_plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`carreer_plan` (
  `cap_id` INT(11) NOT NULL AUTO_INCREMENT,
  `cap_plan` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`cap_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `survey`.`certification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`certification` (
  `cert_id` INT(11) NOT NULL AUTO_INCREMENT,
  `cert_name` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`cert_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `survey`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`country` (
  `ctr_id` INT(11) NOT NULL AUTO_INCREMENT,
  `ctr_name` VARCHAR(42) NULL DEFAULT NULL,
  PRIMARY KEY (`ctr_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 98
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `survey`.`db`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`db` (
  `db_id` INT(11) NOT NULL AUTO_INCREMENT,
  `db_name` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`db_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `survey`.`education`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`education` (
  `edu_id` INT(11) NOT NULL AUTO_INCREMENT,
  `edu_title` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`edu_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `survey`.`employment_sector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`employment_sector` (
  `sec_id` INT(11) NOT NULL AUTO_INCREMENT,
  `sec_name` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`sec_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `survey`.`employment_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`employment_status` (
  `emp_id` INT(11) NOT NULL AUTO_INCREMENT,
  `emp_status` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`emp_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `survey`.`how_many_companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`how_many_companies` (
  `mcp_id` INT(11) NOT NULL AUTO_INCREMENT,
  `mcp_many_companies` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`mcp_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `survey`.`job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`job` (
  `job_id` INT(11) NOT NULL AUTO_INCREMENT,
  `job_name` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`job_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `survey`.`largest_city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`largest_city` (
  `pop_id` INT(11) NOT NULL AUTO_INCREMENT,
  `pop_name` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`pop_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `survey`.`looking_job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`looking_job` (
  `look_id` INT(11) NOT NULL AUTO_INCREMENT,
  `look_job` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`look_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `survey`.`sondage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`sondage` (
  `sdg_id` INT(11) NOT NULL AUTO_INCREMENT,
  `sdg_year` SMALLINT(6) NULL DEFAULT NULL,
  PRIMARY KEY (`sdg_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `survey`.`sondage_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`sondage_item` (
  `sgi_id` INT(11) NOT NULL AUTO_INCREMENT,
  `timestamp` DATETIME NULL DEFAULT NULL,
  `salary_usd` DECIMAL(10,2) NULL DEFAULT NULL,
  `postal_code` VARCHAR(50) NULL DEFAULT NULL,
  `years_with_db` INT(11) NULL DEFAULT NULL,
  `manage_staff` SMALLINT(6) NULL DEFAULT NULL,
  `years_with_job` SMALLINT(6) NULL DEFAULT NULL,
  `other_people` INT(11) NULL DEFAULT NULL,
  `company_employee` VARCHAR(150) NULL DEFAULT NULL,
  `database_servers` INT(11) NULL DEFAULT NULL,
  `education_computer` SMALLINT(6) NULL DEFAULT NULL,
  `hours_worked` INT(11) NULL DEFAULT NULL,
  `telecommute` INT(11) NULL DEFAULT NULL,
  `newest_version` VARCHAR(100) NULL DEFAULT NULL,
  `oldest_version` VARCHAR(100) NULL DEFAULT NULL,
  `gender` VARCHAR(100) NULL DEFAULT NULL,
  `ctr_id` INT(11) NULL DEFAULT NULL,
  `sdg_id` INT(11) NULL DEFAULT NULL,
  `pop_id` INT(11) NULL DEFAULT NULL,
  `edu_id` INT(11) NULL DEFAULT NULL,
  `look_id` INT(11) NULL DEFAULT NULL,
  `cap_id` INT(11) NULL DEFAULT NULL,
  `cert_id` INT(11) NULL DEFAULT NULL,
  `mcp_id` INT(11) NULL DEFAULT NULL,
  `emp_id` INT(11) NULL DEFAULT NULL,
  `sec_id` INT(11) NULL DEFAULT NULL,
  `job_id` INT(11) NULL DEFAULT NULL,
  `db_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`sgi_id`),
  INDEX `ctr_id` (`ctr_id` ASC),
  INDEX `sdg_id` (`sdg_id` ASC),
  INDEX `pop_id` (`pop_id` ASC),
  INDEX `edu_id` (`edu_id` ASC),
  INDEX `look_id` (`look_id` ASC),
  INDEX `cap_id` (`cap_id` ASC),
  INDEX `cert_id` (`cert_id` ASC),
  INDEX `mcp_id` (`mcp_id` ASC),
  INDEX `emp_id` (`emp_id` ASC),
  INDEX `sec_id` (`sec_id` ASC),
  INDEX `job_id` (`job_id` ASC),
  INDEX `db_id` (`db_id` ASC),
  CONSTRAINT `sondage_item_ibfk_1`
    FOREIGN KEY (`ctr_id`)
    REFERENCES `survey`.`country` (`ctr_id`),
  CONSTRAINT `sondage_item_ibfk_10`
    FOREIGN KEY (`sec_id`)
    REFERENCES `survey`.`employment_sector` (`sec_id`),
  CONSTRAINT `sondage_item_ibfk_11`
    FOREIGN KEY (`job_id`)
    REFERENCES `survey`.`job` (`job_id`),
  CONSTRAINT `sondage_item_ibfk_12`
    FOREIGN KEY (`db_id`)
    REFERENCES `survey`.`db` (`db_id`),
  CONSTRAINT `sondage_item_ibfk_2`
    FOREIGN KEY (`sdg_id`)
    REFERENCES `survey`.`sondage` (`sdg_id`),
  CONSTRAINT `sondage_item_ibfk_3`
    FOREIGN KEY (`pop_id`)
    REFERENCES `survey`.`largest_city` (`pop_id`),
  CONSTRAINT `sondage_item_ibfk_4`
    FOREIGN KEY (`edu_id`)
    REFERENCES `survey`.`education` (`edu_id`),
  CONSTRAINT `sondage_item_ibfk_5`
    FOREIGN KEY (`look_id`)
    REFERENCES `survey`.`looking_job` (`look_id`),
  CONSTRAINT `sondage_item_ibfk_6`
    FOREIGN KEY (`cap_id`)
    REFERENCES `survey`.`carreer_plan` (`cap_id`),
  CONSTRAINT `sondage_item_ibfk_7`
    FOREIGN KEY (`cert_id`)
    REFERENCES `survey`.`certification` (`cert_id`),
  CONSTRAINT `sondage_item_ibfk_8`
    FOREIGN KEY (`mcp_id`)
    REFERENCES `survey`.`how_many_companies` (`mcp_id`),
  CONSTRAINT `sondage_item_ibfk_9`
    FOREIGN KEY (`emp_id`)
    REFERENCES `survey`.`employment_status` (`emp_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10342
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `survey`.`other_db`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`other_db` (
  `db_id` INT(11) NULL DEFAULT NULL,
  `sgi_id` INT(11) NULL DEFAULT NULL,
  INDEX `db_id` (`db_id` ASC),
  INDEX `sgi_id` (`sgi_id` ASC),
  CONSTRAINT `other_db_ibfk_1`
    FOREIGN KEY (`db_id`)
    REFERENCES `survey`.`db` (`db_id`),
  CONSTRAINT `other_db_ibfk_2`
    FOREIGN KEY (`sgi_id`)
    REFERENCES `survey`.`sondage_item` (`sgi_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `survey`.`other_duties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`other_duties` (
  `job_id` INT(11) NULL DEFAULT NULL,
  `sgi_id` INT(11) NULL DEFAULT NULL,
  INDEX `job_id` (`job_id` ASC),
  INDEX `sgi_id` (`sgi_id` ASC),
  CONSTRAINT `other_duties_ibfk_1`
    FOREIGN KEY (`job_id`)
    REFERENCES `survey`.`job` (`job_id`),
  CONSTRAINT `other_duties_ibfk_2`
    FOREIGN KEY (`sgi_id`)
    REFERENCES `survey`.`sondage_item` (`sgi_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `survey`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`task` (
  `tas_id` INT(11) NOT NULL AUTO_INCREMENT,
  `tas_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`tas_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `survey`.`task_perfomed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`task_perfomed` (
  `tas_id` INT(11) NULL DEFAULT NULL,
  `sgi_id` INT(11) NULL DEFAULT NULL,
  INDEX `tas_id` (`tas_id` ASC),
  INDEX `sgi_id` (`sgi_id` ASC),
  CONSTRAINT `task_perfomed_ibfk_1`
    FOREIGN KEY (`tas_id`)
    REFERENCES `survey`.`task` (`tas_id`),
  CONSTRAINT `task_perfomed_ibfk_2`
    FOREIGN KEY (`sgi_id`)
    REFERENCES `survey`.`sondage_item` (`sgi_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
